export const FETCH_MUSIC = 'FETCH_MUSIC';
export const FETCH_MUSIC_SUCCESS = 'FETCH_MUSIC_SUCCESS';
export const FETCH_MUSIC_FAILURE = 'FETCH_MUSIC_FAILURE';

export const PLAY_MUSIC = 'PLAY_MUSIC';
export const PLAY_MUSIC_SUCCESS = 'PLAY_MUSIC_SUCCESS';
export const PLAY_MUSIC_FAILURE = 'PLAY_MUSIC_FAILURE';

export const PAUSE_MUSIC = 'PAUSE_MUSIC';
export const PAUSE_MUSIC_SUCCESS = 'PAUSE_MUSIC_SUCCESS';
export const PAUSE_MUSIC_FAILURE = 'PAUSE_MUSIC_FAILURE';

export const NEXT_SONG = 'NEXT_SONG';
export const NEXT_SONG_SUCCESS = 'NEXT_SONG_SUCCESS';
export const NEXT_SONG_FAILURE = 'NEXT_SONG_FAILURE';

export const PREV_SONG = 'PREV_SONG';
export const PREV_SONG_SUCCESS = 'PREV_SONG_SUCCESS';
export const PREV_SONG_FAILURE = 'PREV_SONG_FAILURE';

export const SHUFFLE_MUSIC = 'SHUFFLE_MUSIC';
export const REPEAT_MUSIC = 'REPEAT_MUSIC';
export const SET_TIME = 'SET_TIME';
export const SET_DURATION = 'SET_DURATION';

export const FETCH_DAILY = 'FETCH_DAILY';
export const FETCH_DAILY_SUCCESS = 'FETCH_DAILY_SUCCESS';
export const FETCH_DAILY_FAILURE = 'FETCH_DAILY_FAILURE';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const USER_UPDATED = 'USER_UPDATED';
export const USER_UPDATED_SUCCESS = 'USER_UPDATED_SUCCESS';
export const USER_UPDATED_FAILURE = 'USER_UPDATED_FAILURE';

export const fbPermissions = ['email'];
