export const FETCH_MUSIC = 'FETCH_MUSIC';
export const FETCH_MUSIC_SUCCESS = 'FETCH_MUSIC_SUCCESS';
export const FETCH_MUSIC_FAILURE = 'FETCH_MUSIC_FAILURE';

export const FETCH_DAILY = 'FETCH_DAILY';
export const FETCH_DAILY_SUCCESS = 'FETCH_DAILY_SUCCESS';
export const FETCH_DAILY_FAILURE = 'FETCH_DAILY_FAILURE';

export const FETCH_PLAYLIST = 'FETCH_PLAYLIST';
export const FETCH_PLAYLIST_SUCCESS = 'FETCH_PLAYLIST_SUCCESS';
export const FETCH_PLAYLIST_FAILURE = 'FETCH_PLAYLIST_FAILURE';

export const PLAYLIST_ADD = 'PLAYLIST_ADD';
export const PLAYLIST_REMOVE = 'PLAYLIST_REMOVE';

export const ADD_HEART = 'ADD_HEART';
export const REMOVE_HEART = 'REMOVE_HEART';

export const GLOBAL_PLAY = 'GLOBAL_PLAY';
export const PLAY_MUSIC = 'PLAY_MUSIC';
export const PAUSE_MUSIC = 'PAUSE_MUSIC';
export const NEXT_SONG = 'NEXT_SONG';
export const PREV_SONG = 'PREV_SONG';
export const TOGGLE_SHUFFLE = 'TOGGLE_SHUFFLE';
export const TOGGLE_REPEAT = 'TOGGLE_REPEAT';
export const SET_TIME = 'SET_TIME';
export const SET_DURATION = 'SET_DURATION';
export const SEEK_TIME = 'SEEK_TIME';

export const ADD_TRACK = 'ADD_TRACK';
export const ADD_TRACK_SUCCESS = 'ADD_TRACK_SUCCESS';
export const ADD_TRACK_FAILURE = 'ADD_TRACK_FAILURE';

export const SEARCH = 'SEARCH';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const USER_UPDATED = 'USER_UPDATED';
export const USER_UPDATED_SUCCESS = 'USER_UPDATED_SUCCESS';
export const USER_UPDATED_FAILURE = 'USER_UPDATED_FAILURE';

export const fbPermissions = ['email'];
